import { Car } from "@/types";

export const carsData: Omit<Car, "id" | "listingType" | "salePrice" | "mileage" | "year" | "condition" | "status">[] = [
  {
    slug: "bmw-7-series",
    name: "BMW 7 Series",
    brand: "BMW",
    category: "luxury",
    tagline: "The pinnacle of driving luxury",
    description:
      "The BMW 7 Series redefines executive luxury with its powerful engine, sophisticated technology, and first-class interior. Perfect for business travel or special occasions.",
    dailyRate: 28900,
    depositAmount: 100000,
    seats: 5,
    doors: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 375,
    acceleration: "0-60 in 4.8s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/bmw-7-series.png",
    galleryUrls: [],
    featured: true,
    available: true,
  },
  {
    slug: "mercedes-g-class",
    name: "Mercedes-Benz G-Class",
    brand: "Mercedes-Benz",
    category: "luxury",
    tagline: "Iconic. Unstoppable. Luxurious.",
    description:
      "The G-Class combines legendary off-road capability with the refinement of a luxury sedan. A statement vehicle that commands attention wherever it goes.",
    dailyRate: 34900,
    depositAmount: 125000,
    seats: 5,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 416,
    acceleration: "0-60 in 5.6s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/mercedes-g-class.png",
    galleryUrls: [],
    featured: true,
    available: true,
  },
  {
    slug: "ford-mustang-convertible",
    name: "Ford Mustang Convertible",
    brand: "Ford",
    category: "convertible",
    tagline: "Feel the freedom",
    description:
      "Drop the top and feel the wind. The Mustang Convertible delivers iconic American muscle with the thrill of open-air driving.",
    dailyRate: 18900,
    depositAmount: 75000,
    seats: 4,
    doors: 2,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 310,
    acceleration: "0-60 in 5.1s",
    luggage: "1 suitcase, 2 bags",
    imageUrl: "/cars/ford-mustang.png",
    galleryUrls: [],
    featured: true,
    available: true,
  },
  {
    slug: "bmw-4-convertible",
    name: "BMW 4 Series Convertible",
    brand: "BMW",
    category: "convertible",
    tagline: "Open-air luxury",
    description:
      "The BMW 4 Series Convertible combines elegant design with exhilarating performance. Its hardtop retractable roof transforms it from coupe to convertible in seconds.",
    dailyRate: 21900,
    depositAmount: 80000,
    seats: 4,
    doors: 2,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 255,
    acceleration: "0-60 in 5.3s",
    luggage: "1 suitcase, 2 bags",
    imageUrl: "/cars/bmw-4-convertible.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "bmw-4-coupe",
    name: "BMW 4 Series Coupe",
    brand: "BMW",
    category: "coupe",
    tagline: "Precision meets passion",
    description:
      "Sleek, sporty, and sophisticated. The BMW 4 Series Coupe offers a thrilling driving experience wrapped in a stunning two-door design.",
    dailyRate: 19900,
    depositAmount: 75000,
    seats: 4,
    doors: 2,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 255,
    acceleration: "0-60 in 5.3s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/bmw-4-coupe.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "bmw-2-coupe",
    name: "BMW 2 Series Coupe",
    brand: "BMW",
    category: "coupe",
    tagline: "Compact. Athletic. Fun.",
    description:
      "The BMW 2 Series Coupe proves that great things come in small packages. Agile handling and rear-wheel drive make every corner a joy.",
    dailyRate: 14900,
    depositAmount: 60000,
    seats: 4,
    doors: 2,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 255,
    acceleration: "0-60 in 5.5s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/bmw-2-coupe.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "chevrolet-suburban",
    name: "Chevrolet Suburban",
    brand: "Chevrolet",
    category: "suv",
    tagline: "Room for the whole crew",
    description:
      "Americas favorite full-size SUV. The Suburban offers exceptional passenger and cargo space, making it perfect for family road trips or group travel.",
    dailyRate: 15900,
    depositAmount: 60000,
    seats: 8,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 355,
    acceleration: "0-60 in 6.7s",
    luggage: "4 suitcases",
    imageUrl: "/cars/chevrolet-suburban.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "jeep-wrangler",
    name: "Jeep Wrangler",
    brand: "Jeep",
    category: "suv",
    tagline: "Go anywhere. Do anything.",
    description:
      "The Jeep Wrangler is the ultimate adventure vehicle. Removable doors and roof, legendary 4x4 capability, and rugged style for those who refuse to stay on the beaten path.",
    dailyRate: 13900,
    depositAmount: 55000,
    seats: 5,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 285,
    acceleration: "0-60 in 6.8s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/jeep-wrangler.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "toyota-camry",
    name: "Toyota Camry",
    brand: "Toyota",
    category: "sedan",
    tagline: "Reliable. Refined. Ready.",
    description:
      "The Toyota Camry is the benchmark for mid-size sedans. Smooth ride, excellent fuel economy, and proven reliability make it the smart choice.",
    dailyRate: 7900,
    depositAmount: 35000,
    seats: 5,
    doors: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 203,
    acceleration: "0-60 in 7.6s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/toyota-camry.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "nissan-versa",
    name: "Nissan Versa",
    brand: "Nissan",
    category: "sedan",
    tagline: "Smart value, big comfort",
    description:
      "Dont let its compact size fool you — the Nissan Versa offers surprising interior space, modern tech, and exceptional fuel efficiency at an unbeatable daily rate.",
    dailyRate: 4900,
    depositAmount: 25000,
    seats: 5,
    doors: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 122,
    acceleration: "0-60 in 9.4s",
    luggage: "1 suitcase, 2 bags",
    imageUrl: "/cars/nissan-versa.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "chrysler-pacifica",
    name: "Chrysler Pacifica",
    brand: "Chrysler",
    category: "van",
    tagline: "Family travel, elevated",
    description:
      "The Chrysler Pacifica is the ultimate family minivan. Stow-and-go seating, dual entertainment screens, and a smooth ride make every family trip enjoyable.",
    dailyRate: 11900,
    depositAmount: 50000,
    seats: 7,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 287,
    acceleration: "0-60 in 7.3s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/chrysler-pacifica.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "toyota-tacoma",
    name: "Toyota Tacoma",
    brand: "Toyota",
    category: "truck",
    tagline: "Built for the long haul",
    description:
      "The Toyota Tacoma is the mid-size truck that does it all. Whether hauling gear to the mountains or navigating city streets, the Tacoma is always up for the challenge.",
    dailyRate: 12900,
    depositAmount: 50000,
    seats: 5,
    doors: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 278,
    acceleration: "0-60 in 7.7s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/toyota-tacoma.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "mercedes-a-class",
    name: "Mercedes-Benz A-Class",
    brand: "Mercedes-Benz",
    category: "sedan",
    tagline: "Entry to luxury",
    description:
      "The Mercedes A-Class brings luxury to the compact segment. MBUX infotainment, premium materials, and that unmistakable Mercedes quality — at an accessible price point.",
    dailyRate: 8900,
    depositAmount: 40000,
    seats: 5,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 188,
    acceleration: "0-60 in 7.0s",
    luggage: "3 bags",
    imageUrl: "/cars/mercedes-a-class.png",
    galleryUrls: [],
    featured: true,
    available: true,
  },
  {
    slug: "bmw-1-series",
    name: "BMW 1 Series",
    brand: "BMW",
    category: "sedan",
    tagline: "The joy of driving, distilled",
    description:
      "The BMW 1 Series packs the signature BMW driving experience into a compact, efficient package. Perfect for city driving with the premium feel you expect.",
    dailyRate: 7900,
    depositAmount: 35000,
    seats: 5,
    doors: 5,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 178,
    acceleration: "0-60 in 7.3s",
    luggage: "3 bags",
    imageUrl: "/cars/bmw-1-series.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
  {
    slug: "mercedes-a-class-sedan",
    name: "Mercedes-Benz A-Class Sedan",
    brand: "Mercedes-Benz",
    category: "sedan",
    tagline: "Elegance in every line",
    description:
      "The A-Class Sedan takes the compact luxury concept and adds a dash of traditional three-box elegance. A longer trunk and sleek profile for those who prefer the classic sedan shape.",
    dailyRate: 9500,
    depositAmount: 42000,
    seats: 5,
    doors: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    horsepower: 188,
    acceleration: "0-60 in 7.0s",
    luggage: "2 suitcases, 2 bags",
    imageUrl: "/cars/mercedes-a-class-sedan.png",
    galleryUrls: [],
    featured: false,
    available: true,
  },
];

export const locationsData = [
  { name: "LAX Airport", address: "1 World Way, Los Angeles, CA 90045", city: "Los Angeles" },
  { name: "JFK Airport", address: "Queens, NY 11430", city: "New York" },
  { name: "Miami International Airport", address: "2100 NW 42nd Ave, Miami, FL 33142", city: "Miami" },
  { name: "San Francisco Airport", address: "San Francisco, CA 94128", city: "San Francisco" },
  { name: "Downtown Los Angeles", address: "800 S Figueroa St, Los Angeles, CA 90017", city: "Los Angeles" },
  { name: "Manhattan - Midtown", address: "310 W 40th St, New York, NY 10018", city: "New York" },
  { name: "Miami Beach", address: "1111 Lincoln Rd, Miami Beach, FL 33139", city: "Miami" },
  { name: "Las Vegas Strip", address: "3570 S Las Vegas Blvd, Las Vegas, NV 89109", city: "Las Vegas" },
];
